import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    name: "Red Tape",
    price: 7599,
    img: "IMG_20220330_223055-01.jpeg",
    size: "S",
    currency: "INR",
    category: "Men",
    productCategory: "Ankle",
    details: `Closure Type : Zipper`,
    rating: 4,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "LAREDO",
    price: 25295,
    img: "",
    size: "L",
    currency: "INR",
    category: "Women",
    productCategory: "Cowboy",
    details: `
        Closure type : Pull-On`,
    rating: 4.4,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Littleplum",
    price: 9299,
    img: "",
    size: "M",
    memory: 128,
    currency: "INR",
    category: "Kids",
    productCategory: "Hiking",
    details: `Closure Type : Hook & Loop`,
    rating: 4.6,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "ARIAT",
    price: 42691,
    img: "",
    size: "XL",
    memory: 128,
    currency: "INR",
    category: "Men",
    productCategory: "Cowboy",
    details: `Closure Type : Slip-On`,
    rating: 4.7,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Columbia",
    price: 13999,
    img: "",
    size: "XXL",
    currency: "INR",
    category: "Women",
    productCategory: "Hiking",
    details: "Closure Type : Slip-On",
    rating: 4.3,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Deer Stags",
    price: 18999,
    img: "",
    size: "S",
    currency: "INR",
    category: "Kids",
    productCategory: "Cowboy",
    details: `
    Closure Type : Pull-On`,
    rating: 4.4,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Bacca Bucci",
    price: 2999,
    img: "",
    size: "M",
    currency: "INR",
    category: "Men",
    productCategory: "Hiking",
    details: `
    Closure Type : Lace-Up`,
    rating: 4,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Metro",
    price: 1795,
    img: "",
    size: "M",
    currency: "INR",
    category: "Women",
    productCategory: "Ankle",
    details: `
    Closure Type : Zip`,
    rating: 4.2,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "KazarMax",
    price: 2999,
    img: "",
    size: "L",
    currency: "INR",
    category: "Kids",
    productCategory: "Ankle",
    details: `
    Closure Type : Lace-Up`,
    rating: 3.8,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Ankle Cooper",
    price: 3999,
    img: "IMG_20220330_223055-01.jpeg",
    size: "L",
    currency: "INR",
    category: "Men",
    productCategory: "Ankle",
    details: `Closure Type : Lace-Up`,
    rating: 4,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "DREAM PAIRS",
    price: 25268,
    img: "IMG_20220330_223055-01.jpeg",
    size: "S",
    currency: "INR",
    category: "Women",
    productCategory: "Cowboy",
    details: `Closure Type : Pull-On`,
    rating: 4.6,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Mishansha",
    price: 12999,
    img: "IMG_20220330_223055-01.jpeg",
    size: "XXL",
    currency: "INR",
    category: "Kids",
    productCategory: "Hiking",
    details: `Closure Type : Hook & Loop`,
    rating: 4.3,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Delize",
    price: 8999,
    img: "IMG_20220330_223055-01.jpeg",
    size: "XXL",
    currency: "INR",
    category: "Men",
    productCategory: "Cowboy",
    details: `Closure Type : Zip`,
    rating: 3.8,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Adidas",
    price: 6522,
    img: "IMG_20220330_223055-01.jpeg",
    size: "Xl",
    currency: "INR",
    category: "Women",
    productCategory: "Hiking",
    details: `Closure Type : Lace-Up`,
    rating: 3.4,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Apakowa",
    price: 6799,
    img: "IMG_20220330_223055-01.jpeg",
    size: "XL",
    currency: "INR",
    category: "Kids",
    productCategory: "Cowboy",
    details: `Closure Type : Hook & loop`,
    rating: 4.2,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "ASIAN",
    price: 1999,
    img: "IMG_20220330_223055-01.jpeg",
    size: "L",
    currency: "INR",
    category: "Men",
    productCategory: "Hiking",
    details: `Closure Type : Lace-Up`,
    rating: 4.3,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "ROCIA",
    price: 3990,
    img: "IMG_20220330_223055-01.jpeg",
    size: "L",
    currency: "INR",
    category: "Women",
    productCategory: "Ankle",
    details: `Closure Type : Pull On`,
    rating: 3.7,
    quantity: 0,
  },
  {
    id: uuid(),
    name: "Woodland",
    price: 4295,
    img: "IMG_20220330_223055-01.jpeg",
    size: "M",
    currency: "INR",
    category: "Kids",
    productCategory: "Ankle",
    details: `Closure Type : Lace-UP`,
    rating: 3.7,
    quantity: 0,
  },
];
